### ISSUE TITLE
React Logical Error

### ISSUE THREAD

**Issue by dhruvkjain** [dhruvkjain/react-calculator#1]
I am new to React and faced some logical error which is as follows,
If you take a look at my App.js, you will find an onButtonPress function in which I have console logged this.state.display after updating the display state by this.setState(), But the issue here is when I click, for example, 1 and then 2, after 2 is clicked, 1 is console logged, But as I have already added 2 to my display state it should console log 12 after I have clicked 2.
I have a rough idea of another method which is "useState" for functions but, I have used class in App.js and am curious to learn to code this way. 

Therefore I would appreciate your help in this regard.

I have uploaded a video of my issue below.
https://github.com/dhruvkjain/react-calculator/assets/138356622/5d18edc5-9ca3-49da-8c93-18406a668ca8

**Comment by Harsh-0986** [comment]
Update the code using the commands 
```bash
git add .
git commit -am "<your message here>"
git push
```

**Comment by dhruvkjain** [comment]
I understood the workflow of code ( from https://www.youtube.com/watch?v=-bEzt5ISACA ) , and made changes accordingly .
